- kind: Vault
  type: hashicorp
  name: hashicorp-quorum
  specs:
    mount_point: quorum
    address: http://vault:8200
    token: DevVaultToken
    namespace: ''
- kind: Store
  type: key
  name: orchestrate-keystore
  specs:
    vault: hashicorp-quorum
- kind: Store
  type: ethereum
  name: orchestrate-eth
  specs:
    key_store: orchestrate-keystore
